---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: "^(app/|src/)"
        args:
          - "--ignore-missing-imports"
          - "--install-types"
          - "--non-interactive"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        files: "^(app/)"
        args:
          - "-q"
          - "-s"
          - "B101,B404,B603,B607"

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-gfm]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: "^(app/)"
        stages: [manual]
        args:
          - "--ignore=D100,D101,D102,D103,D104,D105,D106,D107,D205,D400"

  - repo: local
    hooks:
      - id: memory-check
        name: memory-check
        entry: python scripts/tools/memory_check.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: memory-index
        name: memory-index
        entry: python scripts/tools/memory_index.py
        language: system
        pass_filenames: false
        stages: [pre-commit]

exclude: |
  ^(venv/|\.venv/|env/|data/|ProjectDocs/)
