-- 备份表: quality_code_dict
-- 时间: 2025-10-30 22:12:31
-- 行数: 34
-- MD5: 08e3451705b5f20585525b6555303eb6

INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (131, '上饱和', '数值特性', 3, '接近量程上限持续') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (132, '下饱和', '数值特性', 3, '接近量程下限持续') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (201, '高噪声', '噪声/完整性', 2, '短窗标准差异常偏高') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (401, '状态矛盾', '跨指标/跨设备', 4, '运行=0但功率/流量高或运行=1但输出近零') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (501, '时间漂移', '时间一致性', 2, 'ts_raw 与 ts_bucket 偏差过大') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (502, '重复秒', '时间一致性', 2, '同秒重复/冲突') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (701, '功率因数异常', '机理/物理', 3, '功率因数超出合理范围') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (711, '液位流量守恒异常', '机理/物理', 4, 'dLevel/dt 与流量不一致') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (721, '相似定律异常', '机理/物理', 3, '与变频相似定律偏差过大') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (731, '泵曲线偏差', '机理/物理', 3, '与泵特性曲线偏差过大') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (751, '计数器非单调', '机理/物理', 3, '累计量出现回退') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (102, '负值不可能', '数值特性', 3, '物理不可能为负（如流量<0）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (141, '量化步长异常', '数值特性', 2, '出现异常量化阶梯或步长不合理') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (202, '间歇性中断', '噪声/完整性', 2, '密集的断续片段（频繁掉点/抖断）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (300, '段落', '运行阶段', 1, '运行阶段标识（若无独立列可用该段）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (301, '启动中', '运行阶段', 2, '设备启动过渡阶段') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (302, '停止中', '运行阶段', 2, '设备停止过渡阶段') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (303, '临时超调', '运行阶段', 2, '启动/停止过程中的短时超调') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (402, '运行时状态冲突零值', '跨指标/跨设备', 4, '运行=1但功率/流量近似为0') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (403, '传感器间冲突', '跨指标/跨设备', 4, '跨传感器物理/逻辑不一致（如功率高而电流近零）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (503, '稀疏缺秒', '时间一致性', 2, '稀疏缺秒（采集空洞）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (601, '传感器故障', '传感器健康', 4, '传感器失效') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (602, '校准偏差', '传感器健康', 3, '校准漂移/偏移') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (603, '传感器断开', '传感器健康', 4, '传感器断开/掉线') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (702, '三相不平衡', '机理/物理', 3, '三相电流/电压不平衡') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (741, '能量守恒违规', '机理/物理', 4, '能量守恒层面不一致') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (750, '计数器', '机理/物理', 2, '计数器相关异常（父类）') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (801, '规则违规机制', '规则/策略', 3, '违反预设机制约束') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (802, '时间表违规', '规则/策略', 3, '违反调度/时间表') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (803, '禁止状态组合', '规则/策略', 4, '出现被禁止的状态组合') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (101, '越界', '数值特性', 3, '数值超出合理区间') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (111, '异常跳变', '数值特性', 3, '相邻秒差值超阈') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (112, '变化率异常', '数值特性', 3, '相对或绝对变化率超阈') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;
INSERT INTO quality_code_dict (code, label_zh, category, severity, description) VALUES (121, '平台期', '数值特性', 2, '短窗标准差与极差均很小，可能传感器卡死') ON CONFLICT (code) DO UPDATE SET label_zh = EXCLUDED.label_zh, category = EXCLUDED.category, severity = EXCLUDED.severity, description = EXCLUDED.description;