-- 备份表: dim_device_capabilities
-- 时间: 2025-10-31 01:18:21
-- 行数: 6
-- MD5: a8b003f2e8f6f1d3ec917c5488704b7f

INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (1, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (2, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (3, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (4, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (5, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, rated_power_kw, rated_current_a, remark, updated_at, updated_by) VALUES (6, TRUE, 25.0, 50.0, 75.0, 150.0, '自适应SQL脚本生成 - 变频泵', '2025-10-31 00:50:12.720581+08:00', NULL) ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, rated_power_kw = EXCLUDED.rated_power_kw, rated_current_a = EXCLUDED.rated_current_a, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;