-- 备份表: dim_device_capabilities
-- 时间: 2025-11-24 18:21:36
-- 行数: 6
-- MD5: 22899f56b857285857860464806d9cb2

INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (1, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (2, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (3, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (4, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (5, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO dim_device_capabilities (device_id, vfd_enabled, freq_min, freq_max, remark, updated_at, updated_by) VALUES (6, TRUE, 25.0, 50.0, '自适应SQL脚本生成 - 变频泵', '2025-11-24 18:19:33.856598+08:00', 'adaptive_sql_script') ON CONFLICT (device_id) DO UPDATE SET vfd_enabled = EXCLUDED.vfd_enabled, freq_min = EXCLUDED.freq_min, freq_max = EXCLUDED.freq_max, remark = EXCLUDED.remark, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;