-- 备份表: metric_capability_policy
-- 时间: 2025-11-11 13:05:59
-- 行数: 53
-- MD5: 611758caeb71f32d3d6a7b5790ef721f

INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_current_c', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_voltage_c', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_frequency', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_1', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_2', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_3', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_4', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_5', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_temperature_sensor_6', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_1', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_2', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_3', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_4', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_5', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_6', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_7', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_motor_vibration_sensor_8', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_kwh', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_1', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_2', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_3', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_4', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_5', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_temperature_sensor_6', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_active_power', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_1', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_2', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_3', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_4', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_5', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('device_running', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_head', '不能', '需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_outlet_pressure', '可能', '需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_power_factor', '可能', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_inlet_pressure', '可能', '需要', '2025-10-25 20:11:01.647651+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_current_a', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_voltage_a', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_current_b', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_voltage_b', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_6', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_7', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_vibration_sensor_8', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pool_liquid_level', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('water_temperature', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('main_pipeline_cumulative_flow', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('main_pipeline_flow_rate', '可以', '不需要', '2025-09-10 07:47:41.922044+08:00', 'sys') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_flow_rate', '不能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_efficiency', '不能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_speed', '不能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_torque', '不能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('main_pipeline_inlet_pressure', '可能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('main_pipeline_outlet_pressure', '可能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
INSERT INTO metric_capability_policy (metric_key, acquisition_status, compute_flag, updated_at, updated_by) VALUES ('pump_cumulative_flow', '可能', '需要', '2025-10-13 13:15:47.645845+08:00', 'augment-agent') ON CONFLICT (metric_key) DO UPDATE SET acquisition_status = EXCLUDED.acquisition_status, compute_flag = EXCLUDED.compute_flag, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;