name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tools and test deps
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit ruff black mypy bandit pip-audit pytest

      - name: Run pre-commit (all files)
        run: |
          pre-commit run --all-files

      - name: Run quality gate
        run: |
          python scripts/quality_gate.py

      - name: Run tests
        run: |
          pytest -q
