---
name: Commitlint
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional
        shell: bash
      - name: Write commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
        shell: bash
      - name: Lint PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js
