---
name: Commitlint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install commitlint
        shell: bash
        run: npm install --global @commitlint/cli @commitlint/config-conventional
      - name: Write commitlint config
        shell: bash
        run: |
          printf '%s' "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - name: Lint PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js
